version: "3.8"
services:
  dailicorns-database:
    container_name: dailicorns-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: sieun06/dailicorns-database
    environment:
      - MARIADB_DATABASE=dailicorns
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"